# PAQUETES

* Son piezas de codigo que extienden funcionalidades de PYTHON
* Tiene una estructura diseñada para usar funciones y clases
* Vienen en carpetas con codigo .py

Para instalar  o desinstalar paquetes, debemos ir al CMD y colocar el comando:
>pip install/uninstall 'nombre del paquete'

### Importacion de paquetes

In [1]:
#Se debe usar la palabra reservada 'import'
import numpy

In [2]:
numpy.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
#Importar un paquete con un acronimo
import numpy as np

In [4]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#Cargar una funcion especifica de un paquete
from numpy import arange

In [6]:
arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Funcion y metodos

* FUNCION: Instrucciones que regresar algo
* METODO: Intrucciones que trabajan sobre un objeto

In [7]:
A = np.arange(9)

In [8]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
type(A)

numpy.ndarray

In [10]:
#Calculando promedio con FUNCION de numpy
np.mean(A)

4.0

In [11]:
#Calculando promedio con METODO de objeto
A.mean()

4.0

In [12]:
#Transformando arreglo con FUNCION de numpy
np.reshape(A,(3,3)) #Convirtio en un arreglo de 3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
#Transformando arreglo con METODO de objeto
A.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Paquetes basicos para Data Science

Procesamiento de datos:
* Numpy
* SciPy
* Pandas
* PySpark

Visualizacion de datos:
* MatPlotlib
* Seaborn
* Bokeh
* Plotly

Modelos ML o AI:
* Keras
* Sklearn
* PyTorch
* TensorFlow

Mineria de datos:
* Scrappy
* Beautifulsoup
* Flask (web-dev)

![](https://gonzalezgouveia.com/wp-content/uploads/2020/11/paquetes-480x330.png)